### ISSUE TITLE
Вылет при попытке развернуть пустую директорию.

### ISSUE THREAD

**Issue by NoviceF** [Lol4t0/tree-model-example#1]
void FilesystemModel::fetchMore(const QModelIndex &parent)
...
beginInsertRows(parent, 0, children.size() - 1);

при количестве детей равном нулю, получаем begin > end и срабатывает assert в коде qt.

**Comment by Lol4t0** [comment]
У меня проблема не воспроизвродится. Указанный фикс (в отдельной ветке) должен исправить проблему. Можете проверить? Если все ок, то я вмержу изменение в основную ветку

**Comment by NoviceF** [comment]
У меня на ubuntu тоже, однако, на windows 7 для Qt 5.4 она присутствует. Проверить смогу в понедельник на работе.

Я, кстати, сделал так

```
parentInfo->mapped = true;

if (children.isEmpty())
    return;
```

т.к. если детей нет, вроде бы нет смысла выполнять код ниже :)

P.s. когда ждать обещанного на хабре продолжения про прокси модели?!

**Comment by Lol4t0** [comment]
Проблема в том, что в если не выполнить код ниже, то у меня получается как будто развернутая папка, но без содержимого. Это как-то нехорошо выглядит. Если же код выполнить, то кнопка "развернуть (плюсик/стрелочка)" исчезает, и я считаю, что это более правильное поведение.

P.S. В свое время заинтересовавшихся было не так чтоб много, поэтому не стал писать. А сейчас я уже немного отошел от темы, и работаю в другой области.

**Comment by NoviceF** [comment]
Насчёт поведения согласен, не обратил внимания.

Насчёт кода, простите за наглость, оставлю это здесь:

```
const int insrtCnt = children.isEmpty() ?
            0 :
            children.size() - 1;
```

А на счёт статьи, очень жаль, что не написали, инфы по теме просто неприлично мало.

**Comment by Lol4t0** [comment]
Я думал так написать тоже, но потом посчитал, что это какой-то функциональный стиль (а я использую функциональщину полседние 2 года), и на С++ так не пишут. 

В любом случае, тепрь оставлю как есть.

**Comment by NoviceF** [comment]
вот сообщение об ошибке, если что 

ASSERT: "last >= first" in file itemmodels\qabstractitemmodel.cpp, line 2603
Invalid parameter passed to C runtime function.
Invalid parameter passed to C runtime function.

код ошибки 3

Фикс устраняет проблему.
